export const ADD_COUNTER = 'ADD_COUNTER';

export const SUBTRACT_COUNTER = 'SUBTRACT_COUNTER';

export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';

export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const STORE_RESULT = 'STORE_RESULT';

export const DELETE_STORED_RESULT = 'DELETE_STORED_RESULT';